# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58448b1956d0a8f9c92282c623fa3b3ee9b5ca53896c67e502011e2a5220ce280cad23c716533fb1095e8a53ede01a3c0a05cedfcc042008ffbe24fc00cc82f6

test:
  secret_key_base: a95dd6f1684372c8da0647ed75786d3a7ab017b85730a3610b63ffa3d22d1adbccfb25aeb60d559c77eb905efecd1fdb4df3bf11ecd0a9c8852685973c611353

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
